<a href="https://colab.research.google.com/github/akashkumar181/Data_cleaning/blob/main/data_cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tasks to Solve

1️⃣ Data Exploration

Display the first 5 rows of the dataset.

Get the summary information (.info()) about the dataset.

Find the total number of rows and columns in the dataset.
Get column names of the dataset.

2️⃣ Data Cleaning & Filtering

Check for missing values and replace them with "Unknown" if found.

Remove any duplicate rows (if present).

Filter the dataset to show only sales of "Laptops".

Find all transactions where the Price is greater than 700 and Quantity is more than 1.

3️⃣ Data Aggregation & Analysis

Calculate the total revenue (Revenue = Price * Quantity) for each order.

Find the mean, median, and standard deviation of the product prices.

Find the most frequently purchased product.

Find the total revenue generated by each product category.

Find the total number of unique customers.

Find the customer who made the highest purchase (based on total revenue).

4️⃣ Date & Time Analysis

Extract the year and month from the Purchase_Date column.

Find the total sales made in March 2024.

Find the day of the week when most purchases were made.

5️⃣ Data Sorting & Ranking

Sort the dataset by Price in descending order.

Rank the customers based on their total spending.

6️⃣ Data Merging & Grouping

Group the dataset by Product and calculate the total revenue for each product.

Create a new dataframe for customer locations and merge it with the original dataset.

7️⃣ String Operations

Convert all Product names to uppercase.

Check if any customer name contains the letter "A".

8️⃣ Saving & Exporting Data

Save the cleaned dataset as a CSV file named "cleaned_sales_data.csv".

In [91]:
import pandas as pd
import calendar


# Sample dataset
data = {
    'Order_ID': [101, 102, 103, 104, 105, 106, 107, 108],
    'Customer_Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah'],
    'Product': ['Laptop', 'Mobile', 'Laptop', 'Tablet', 'Mobile', 'Laptop', 'Tablet', 'Mobile'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics'],
    'Price': [800, 600, 900, 300, 650, 850, 280, 620],
    'Quantity': [1, 2, 1, 3, 1, 1, 4, 2],
    'Purchase_Date': pd.to_datetime(['2024-01-15', '2024-02-20', '2024-03-05', '2024-01-10', '2024-04-12', '2024-02-28', '2024-03-15', '2024-04-05'])
}

df = pd.DataFrame(data)
print(df)

   Order_ID Customer_Name Product     Category  Price  Quantity Purchase_Date
0       101         Alice  Laptop  Electronics    800         1    2024-01-15
1       102           Bob  Mobile  Electronics    600         2    2024-02-20
2       103       Charlie  Laptop  Electronics    900         1    2024-03-05
3       104         David  Tablet  Electronics    300         3    2024-01-10
4       105           Eva  Mobile  Electronics    650         1    2024-04-12
5       106         Frank  Laptop  Electronics    850         1    2024-02-28
6       107         Grace  Tablet  Electronics    280         4    2024-03-15
7       108        Hannah  Mobile  Electronics    620         2    2024-04-05

In [61]:
df.head(5)

,Order_ID,Customer_Name,Product,Category,Price,Quantity,Purchase_Date,Location
0,101,Alice,Laptop,Electronics,800,1,2024-01-15,New York
1,102,Bob,Mobile,Electronics,600,2,2024-02-20,Los Angeles
2,103,Charlie,Laptop,Electronics,900,1,2024-03-05,New York
3,104,David,Tablet,Electronics,300,3,2024-01-10,Chicago
4,105,Eva,Mobile,Electronics,650,1,2024-04-12,Houston

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       8 non-null      int64
 1   Customer_Name  8 non-null      object
 2   Product        8 non-null      object
 3   Category       8 non-null      object
 4   Price          8 non-null      int64
 5   Quantity       8 non-null      int64
 6   Purchase_Date  8 non-null      datetime64[ns]
 7   Location       8 non-null      object
dtypes: datetime64[ns](1), int64(3), object(4)
memory usage: 644.0+ bytes

In [62]:
df.shape[0]

8

In [12]:
df.shape[1]

8

In [13]:
df.columns

Index(['Order_ID', 'Customer_Name', 'Product', 'Category', 'Price', 'Quantity',
       'Purchase_Date', 'Location'],
      dtype='object')

In [14]:
df.isnull().sum()

Order_ID         0
Customer_Name    0
Product          0
Category         0
Price            0
Quantity         0
Purchase_Date    0
Location         0
dtype: int64

In [63]:
df.drop_duplicates(inplace=True)
df

,Order_ID,Customer_Name,Product,Category,Price,Quantity,Purchase_Date,Location
0,101,Alice,Laptop,Electronics,800,1,2024-01-15,New York
1,102,Bob,Mobile,Electronics,600,2,2024-02-20,Los Angeles
2,103,Charlie,Laptop,Electronics,900,1,2024-03-05,New York
3,104,David,Tablet,Electronics,300,3,2024-01-10,Chicago
4,105,Eva,Mobile,Electronics,650,1,2024-04-12,Houston
5,106,Frank,Laptop,Electronics,850,1,2024-02-28,Chicago
6,107,Grace,Tablet,Electronics,280,4,2024-03-15,Houston
7,108,Hannah,Mobile,Electronics,620,2,2024-04-05,Los Angeles

In [64]:
laptop=df[df['Product']=='Laptop']
laptop

,Order_ID,Customer_Name,Product,Category,Price,Quantity,Purchase_Date,Location
0,101,Alice,Laptop,Electronics,800,1,2024-01-15,New York
2,103,Charlie,Laptop,Electronics,900,1,2024-03-05,New York
5,106,Frank,Laptop,Electronics,850,1,2024-02-28,Chicago

In [65]:
trans=df[(df["Price"]>700) & (df["Quantity"]>1)]
print(trans)

Empty DataFrame
Columns: [Order_ID, Customer_Name, Product, Category, Price, Quantity, Purchase_Date, Location]
Index: []

In [105]:

Totalrev=df['Price']*df['Quantity'].sum()
print(Totalrev)
x=df['Price'].mean().sum()
print("Mean:",x)
y=df['Price'].median()
print("Medain:",y)
z=df["Price"].std()
print("Standard Deviation:",z)
TotalrevEach=df['Price']*df['Quantity']
df["TotalrevEach"]=TotalrevEach
print(TotalrevEach)
max_count = df['Product'].value_counts().max()

most_frequent_products = df['Product'].value_counts()[df['Product'].value_counts() == max_count]
print(most_frequent_products)
uniquecust=df["Customer_Name"].nunique()
print(uniquecust)
print("Customer who made the highest purchase")
x=df.groupby("Customer_Name")["TotalrevEach"].sum().idxmax()
print(x)
df['Purchase_Date']=pd.to_datetime(df['Purchase_Date'])
df['year']=df['Purchase_Date'].dt.year
df['month']=df['Purchase_Date'].dt.month
df['day_of_week']=df['Purchase_Date'].dt.dayofweek
df['day_name']=df['Purchase_Date'].dt.day_name()

totalsalesinMarch = df[(df["month"] == "March") & (df["year"]==2024)]["TotalrevEach"].sum()

print("Total sales in March:", totalsalesinMarch)
mostsalesofDay=df.groupby("day_name")["TotalrevEach"].sum().idxmax()
print("Most sales of day:",mostsalesofDay)
x=df.sort_values(by="Price",ascending=False)
print(x)
df["Rank"]=df["TotalrevEach"].rank()


print("PRODUCT Sorting")

x=df.groupby("Product")["TotalrevEach"].sum()
print(x)
dfnew=pd.DataFrame({'Customer_Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Frank', 'Grace', 'Hannah'],
                    'Location': ['New York', 'Los Angeles', 'New York', 'Chicago', 'Houston', 'Chicago', 'Houston', 'Los Angeles']
                    })
df.merge(dfnew,on="Customer_Name",how='left')
df["Product"]=df["Product"].str.upper()
x=df[df['Customer_Name'].str.contains('A')]["Customer_Name"].values[0]
print(x)
df

0    12000
1     9000
2    13500
3     4500
4     9750
5    12750
6     4200
7     9300
Name: Price, dtype: int64
Mean: 625.0
Medain: 635.0
Standard Deviation: 233.84976862446172
0     800
1    1200
2     900
3     900
4     650
5     850
6    1120
7    1240
dtype: int64
Product
LAPTOP    3
MOBILE    3
Name: count, dtype: int64
8
Customer who made the highest purchase
Hannah
Total sales in March: 0
Most sales of day: Friday
   Order_ID Customer_Name Product     Category  Price  Quantity Purchase_Date  \
2       103       Charlie  LAPTOP  Electronics    900         1    2024-03-05
5       106         Frank  LAPTOP  Electronics    850         1    2024-02-28
0       101         Alice  LAPTOP  Electronics    800         1    2024-01-15
4       105           Eva  MOBILE  Electronics    650         1    2024-04-12
7       108        Hannah  MOBILE  Electronics    620         2    2024-04-05
1       102           Bob  MOBILE  Electronics    600         2    2024-02-20
3       104         David  TABLET  Electronics    300         3    2024-01-10
6       107         Grace  TABLET  Electronics    280         4    2024-03-15

   TotalrevEach  year  month  day_of_week   day_name  Rank
2           900  2024      3            1    Tuesday   4.5
5           850  2024      2            2  Wednesday   3.0
0           800  2024      1            0     Monday   2.0
4           650  2024      4            4     Friday   1.0
7          1240  2024      4            4     Friday   8.0
1          1200  2024      2            1    Tuesday   7.0
3           900  2024      1            2  Wednesday   4.5
6          1120  2024      3            4     Friday   6.0
PRODUCT Sorting
Product
LAPTOP    2550
MOBILE    3090
TABLET    2020
Name: TotalrevEach, dtype: int64
Alice

,Order_ID,Customer_Name,Product,Category,Price,Quantity,Purchase_Date,TotalrevEach,year,month,day_of_week,day_name,Rank
0,101,Alice,LAPTOP,Electronics,800,1,2024-01-15,800,2024,1,0,Monday,2.0
1,102,Bob,MOBILE,Electronics,600,2,2024-02-20,1200,2024,2,1,Tuesday,7.0
2,103,Charlie,LAPTOP,Electronics,900,1,2024-03-05,900,2024,3,1,Tuesday,4.5
3,104,David,TABLET,Electronics,300,3,2024-01-10,900,2024,1,2,Wednesday,4.5
4,105,Eva,MOBILE,Electronics,650,1,2024-04-12,650,2024,4,4,Friday,1.0
5,106,Frank,LAPTOP,Electronics,850,1,2024-02-28,850,2024,2,2,Wednesday,3.0
6,107,Grace,TABLET,Electronics,280,4,2024-03-15,1120,2024,3,4,Friday,6.0
7,108,Hannah,MOBILE,Electronics,620,2,2024-04-05,1240,2024,4,4,Friday,8.0

   Order_ID Customer_Name Product     Category  Price  Quantity Purchase_Date  \
2       103       Charlie  Laptop  Electronics    900         1    2024-03-05
5       106         Frank  Laptop  Electronics    850         1    2024-02-28
0       101         Alice  Laptop  Electronics    800         1    2024-01-15
4       105           Eva  Mobile  Electronics    650         1    2024-04-12
7       108        Hannah  Mobile  Electronics    620         2    2024-04-05
1       102           Bob  Mobile  Electronics    600         2    2024-02-20
3       104         David  Tablet  Electronics    300         3    2024-01-10
6       107         Grace  Tablet  Electronics    280         4    2024-03-15

      Location  TotalrevEach  year  month  day_of_week   day_name
2     New York           900  2024      3            1    Tuesday
5      Chicago           850  2024      2            2  Wednesday
0     New York           800  2024      1            0     Monday
4      Houston           650  2024      4            4     Friday
7  Los Angeles          1240  2024      4            4     Friday
1  Los Angeles          1200  2024      2            1    Tuesday
3      Chicago           900  2024      1            2  Wednesday
6      Houston          1120  2024      3            4     Friday